// Package attr provides prebound constructors for common HTML
// attributes. Each string-valued attribute is a partial application
// of [domi.Name]; each boolean attribute is a partial application of
// [domi.Bool].
//
// Attribute combining rules (class joining, style joining, first-wins
// for others) are described on [domi.Attr].
package attr

import (
	"fmt"

	"ily.dev/domi"
)

// String-valued attributes.
var (
	Accept              = domi.Name("accept")
	AcceptCharset       = domi.Name("accept-charset")
	AccessKey           = domi.Name("accesskey")
	Action              = domi.Name("action")
	Alt                 = domi.Name("alt")
	Autocapitalize      = domi.Name("autocapitalize")
	Autocomplete        = domi.Name("autocomplete")
	Blocking            = domi.Name("blocking")
	Charset             = domi.Name("charset")
	Cite                = domi.Name("cite")
	Class               = domi.Name("class")
	Cols                = domi.Name("cols")
	Colspan             = domi.Name("colspan")
	Content             = domi.Name("content")
	CrossOrigin         = domi.Name("crossorigin")
	Datetime            = domi.Name("datetime")
	Decoding            = domi.Name("decoding")
	Dir                 = domi.Name("dir")
	Download            = domi.Name("download")
	Enctype             = domi.Name("enctype")
	EnterKeyHint        = domi.Name("enterkeyhint")
	FetchPriority       = domi.Name("fetchpriority")
	For                 = domi.Name("for")
	Form                = domi.Name("form")
	FormAction          = domi.Name("formaction")
	FormEnctype         = domi.Name("formenctype")
	FormMethod          = domi.Name("formmethod")
	FormTarget          = domi.Name("formtarget")
	Headers             = domi.Name("headers")
	Height              = domi.Name("height")
	High                = domi.Name("high")
	Href                = domi.Name("href")
	HrefLang            = domi.Name("hreflang")
	ID                  = domi.Name("id")
	InputMode           = domi.Name("inputmode")
	Integrity           = domi.Name("integrity")
	ItemProp            = domi.Name("itemprop")
	Kind                = domi.Name("kind")
	Label               = domi.Name("label")
	Lang                = domi.Name("lang")
	List                = domi.Name("list")
	Loading             = domi.Name("loading")
	Low                 = domi.Name("low")
	Max                 = domi.Name("max")
	MaxLength           = domi.Name("maxlength")
	Media               = domi.Name("media")
	Method              = domi.Name("method")
	Min                 = domi.Name("min")
	MinLength           = domi.Name("minlength")
	Name                = domi.Name("name")
	Nonce               = domi.Name("nonce")
	Optimum             = domi.Name("optimum")
	Pattern             = domi.Name("pattern")
	Ping                = domi.Name("ping")
	Placeholder         = domi.Name("placeholder")
	Popover             = domi.Name("popover")
	PopoverTarget       = domi.Name("popovertarget")
	PopoverTargetAction = domi.Name("popovertargetaction")
	Poster              = domi.Name("poster")
	Preload             = domi.Name("preload")
	ReferrerPolicy      = domi.Name("referrerpolicy")
	Rel                 = domi.Name("rel")
	Role                = domi.Name("role")
	Rows                = domi.Name("rows")
	Rowspan             = domi.Name("rowspan")
	Sandbox             = domi.Name("sandbox")
	Scope               = domi.Name("scope")
	Size                = domi.Name("size")
	Sizes               = domi.Name("sizes")
	Slot                = domi.Name("slot")
	Span                = domi.Name("span")
	Src                 = domi.Name("src")
	SrcDoc              = domi.Name("srcdoc")
	SrcLang             = domi.Name("srclang")
	SrcSet              = domi.Name("srcset")
	Start               = domi.Name("start")
	Step                = domi.Name("step")
	Style               = domi.Name("style")
	TabIndex            = domi.Name("tabindex")
	Target              = domi.Name("target")
	Title               = domi.Name("title")
	Type                = domi.Name("type")
	Value               = domi.Name("value")
	Width               = domi.Name("width")
	Wrap                = domi.Name("wrap")
)

// Boolean attributes. For standard boolean attributes, present means
// true, absent means false. For enumerated boolean attributes
// (Draggable, Spellcheck, Translate),
// [domi.Bool] emits a keyword value instead.
var (
	Autofocus      = domi.Bool("autofocus")
	Autoplay       = domi.Bool("autoplay")
	Checked        = domi.Bool("checked")
	Controls       = domi.Bool("controls")
	Default        = domi.Bool("default")
	Disabled       = domi.Bool("disabled")
	Draggable      = domi.Bool("draggable")
	FormNoValidate = domi.Bool("formnovalidate")
	Hidden         = domi.Bool("hidden")
	Inert          = domi.Bool("inert")
	Loop           = domi.Bool("loop")
	Multiple       = domi.Bool("multiple")
	Muted          = domi.Bool("muted")
	NoValidate     = domi.Bool("novalidate")
	Open           = domi.Bool("open")
	PlaysInline    = domi.Bool("playsinline")
	Readonly       = domi.Bool("readonly")
	Required       = domi.Bool("required")
	Reversed       = domi.Bool("reversed")
	Selected       = domi.Bool("selected")
	Spellcheck     = domi.Bool("spellcheck")
	Translate      = domi.Bool("translate")
)

// Stylef returns a style attribute formatted with [fmt.Sprintf].
func Stylef(format string, a ...any) domi.Attr {
	return Style(fmt.Sprintf(format, a...))
}
