// Package html provides prebound builders for common HTML elements. App
// authors using a UI component library typically reach for those components
// and the domi.Node type directly; this package is a fallback for ad-hoc
// markup.
//
// Each builder is the result of [domi.Tag], so usage is two curried calls
// — first attributes, then children:
//
//	Div(attr.Class("x"))(Text("hi"), Button(event.Click(msg))(Text("ok")))
//
// For "no children" cases (void elements like Input, or any element used as
// a leaf without nested content), the trailing children call is optional:
//
//	Div()(Text("a"), Br(), Input(attr.Type("text")), Text("b"))
package html

import "ily.dev/domi"

var (
	A          = domi.Tag("a")
	Abbr       = domi.Tag("abbr")
	Address    = domi.Tag("address")
	Article    = domi.Tag("article")
	Aside      = domi.Tag("aside")
	Audio      = domi.Tag("audio")
	B          = domi.Tag("b")
	Blockquote = domi.Tag("blockquote")
	BR         = domi.Tag("br")
	Button     = domi.Tag("button")
	Canvas     = domi.Tag("canvas")
	Caption    = domi.Tag("caption")
	Cite       = domi.Tag("cite")
	Code       = domi.Tag("code")
	Col        = domi.Tag("col")
	ColGroup   = domi.Tag("colgroup")
	Data       = domi.Tag("data")
	DataList   = domi.Tag("datalist")
	DD         = domi.Tag("dd")
	Del        = domi.Tag("del")
	Details    = domi.Tag("details")
	Dfn        = domi.Tag("dfn")
	Dialog     = domi.Tag("dialog")
	Div        = domi.Tag("div")
	DL         = domi.Tag("dl")
	DT         = domi.Tag("dt")
	EM         = domi.Tag("em")
	Embed      = domi.Tag("embed")
	Fieldset   = domi.Tag("fieldset")
	FigCaption = domi.Tag("figcaption")
	Figure     = domi.Tag("figure")
	Footer     = domi.Tag("footer")
	Form       = domi.Tag("form")
	H1         = domi.Tag("h1")
	H2         = domi.Tag("h2")
	H3         = domi.Tag("h3")
	H4         = domi.Tag("h4")
	H5         = domi.Tag("h5")
	H6         = domi.Tag("h6")
	Head       = domi.Tag("head")
	Header     = domi.Tag("header")
	HGroup     = domi.Tag("hgroup")
	HR         = domi.Tag("hr")
	HTML       = domi.Tag("html")
	I          = domi.Tag("i")
	IFrame     = domi.Tag("iframe")
	Img        = domi.Tag("img")
	Input      = domi.Tag("input")
	Ins        = domi.Tag("ins")
	Kbd        = domi.Tag("kbd")
	Label      = domi.Tag("label")
	Legend     = domi.Tag("legend")
	LI         = domi.Tag("li")
	Link       = domi.Tag("link")
	Main       = domi.Tag("main")
	Mark       = domi.Tag("mark")
	Menu       = domi.Tag("menu")
	Meta       = domi.Tag("meta")
	Meter      = domi.Tag("meter")
	Nav        = domi.Tag("nav")
	OL         = domi.Tag("ol")
	OptGroup   = domi.Tag("optgroup")
	Option     = domi.Tag("option")
	Output     = domi.Tag("output")
	P          = domi.Tag("p")
	Picture    = domi.Tag("picture")
	Pre        = domi.Tag("pre")
	Progress   = domi.Tag("progress")
	Q          = domi.Tag("q")
	RP         = domi.Tag("rp")
	RT         = domi.Tag("rt")
	Ruby       = domi.Tag("ruby")
	S          = domi.Tag("s")
	Samp       = domi.Tag("samp")
	Script     = domi.Tag("script")
	Search     = domi.Tag("search")
	Section    = domi.Tag("section")
	Select     = domi.Tag("select")
	Slot       = domi.Tag("slot")
	Small      = domi.Tag("small")
	Source     = domi.Tag("source")
	Span       = domi.Tag("span")
	Strong     = domi.Tag("strong")
	Sub        = domi.Tag("sub")
	Summary    = domi.Tag("summary")
	Sup        = domi.Tag("sup")
	Table      = domi.Tag("table")
	TBody      = domi.Tag("tbody")
	TD         = domi.Tag("td")
	Template   = domi.Tag("template")
	Textarea   = domi.Tag("textarea")
	TFoot      = domi.Tag("tfoot")
	TH         = domi.Tag("th")
	THead      = domi.Tag("thead")
	Time       = domi.Tag("time")
	Title      = domi.Tag("title")
	TR         = domi.Tag("tr")
	Track      = domi.Tag("track")
	U          = domi.Tag("u")
	UL         = domi.Tag("ul")
	Var        = domi.Tag("var")
	Video      = domi.Tag("video")
	Wbr        = domi.Tag("wbr")
)
